# Generated by Django 4.1.2 on 2022-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosharingapp', '0002_profile_uid_alter_comment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
